### ISSUE TITLE
batcher内部如果是多IO操作

### ISSUE THREAD

**Issue by sweat123** [shouweikun/estuary#2]
文档里说`batcher`负责将数据进行处理并打包; 我有一个问题，如果`batcher`里有大量的`IO`操作，框架同步效率是否会有影响。

目前我遇到一个场景，从`kafka`里拉数据，之后这些数据会反查数据库，然后分发给下游。我之前写的同步应用数据量一大，效率就很低。

**Comment by shouweikun** [comment]
(｡･∀･)ﾉﾞ嗨，之前休假没有看到你的issue，是这样的，batcher这里其实是一个batcher的组，可以理解为是一组batcher在干活，并且这个batcher数量是可以调整的，我这里就是batcher最耗时，增加batcher数量性能有明显提升

**Comment by sweat123** [comment]
@shouweikun 好。感觉这是一个有趣的项目 :smile:
